//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVCompanyWpfApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisementShows
    {
        public int AdvertisementShow_Id { get; set; }
        public int Advertisement_Id { get; set; }
        public int Ether_Id { get; set; }
        public double StartTime { get; set; }
        public double EndTime { get; set; }
    
        public virtual Advertisements Advertisements { get; set; }
        public virtual Ethers Ethers { get; set; }
    }
}
