//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVCompanyWpfApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisements()
        {
            this.AdvertisementShows = new HashSet<AdvertisementShows>();
        }
    
        public int Advertisement_Id { get; set; }
        public string Title { get; set; }
        public int DesiredShowTime_Id { get; set; }
        public double Duration { get; set; }
        public double Price { get; set; }
        public int AgeRestriction_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public bool IsPurchased { get; set; }
    
        public virtual AgeRestrictions AgeRestrictions { get; set; }
        public virtual DesiredShowTimes DesiredShowTimes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertisementShows> AdvertisementShows { get; set; }
    }
}
