//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVCompanyWpfApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broadcasts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broadcasts()
        {
            this.TransferShows = new HashSet<TransferShows>();
        }
    
        public int Broadcast_Id { get; set; }
        public string Title { get; set; }
        public int AgeRestriction_Id { get; set; }
        public string Leading { get; set; }
    
        public virtual AgeRestrictions AgeRestrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferShows> TransferShows { get; set; }
    }
}
