//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVCompanyWpfApp.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TVCompanyEntities : DbContext
    {
        public TVCompanyEntities()
            : base("name=TVCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Advertisements> Advertisements { get; set; }
        public virtual DbSet<AdvertisementShows> AdvertisementShows { get; set; }
        public virtual DbSet<AgeRestrictions> AgeRestrictions { get; set; }
        public virtual DbSet<Balances> Balances { get; set; }
        public virtual DbSet<Broadcasts> Broadcasts { get; set; }
        public virtual DbSet<DesiredShowTimes> DesiredShowTimes { get; set; }
        public virtual DbSet<Ethers> Ethers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TransferShows> TransferShows { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
